# Generated by Django 2.0 on 2019-03-14 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20190314_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirrurl',
            name='Updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='kirrurl',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
